
export const tipsData = {
  vendas: [
    "Aborde rápido com sorriso e olhar no olho.",
    "Comece com pergunta aberta: “O que você procura hoje pra te ajudar?”.",
    "Escute primeiro, só ofereça depois de entender a necessidade.",
    "Mostre sempre pelo menos 2 a 3 opções, não só uma.",
    "Apresente primeiro a opção “ideal”, depois a intermediária.",
    "Use benefícios, não só características: “Isso faz você…”.",
    "Teste frases de segurança: “Fica ótimo para o seu dia a dia.”.",
    "No provador, esteja por perto para trazer tamanhos e opções.",
    "Nunca pergunte “Vai levar?”; pergunte “Qual você gostou mais?”.",
    "Se o cliente travar no preço, mostre opções parecidas mais em conta.",
    "Use prova social: “Essa peça sai muito bem para…”.",
    "Mostre só promoções que fazem sentido para o cliente, não todas.",
    "Organize o cabide/mesa na frente do cliente, isso puxa conversa.",
    "Use o nome da pessoa durante o atendimento.",
    "Reforce troca fácil e garantias para tirar o medo de comprar.",
    "Ofereça cadastramento em programa de fidelidade no fechamento.",
    "Se o cliente disser “vou pensar”, combine um retorno: “Posso separar até tal hora?”.",
    "Use o espelho a seu favor: deixe o cliente se ver bem com o produto.",
    "Evite ficar atrás do balcão; fique próximo da área de escolha.",
    "Deixe o celular de lado enquanto tiver cliente na loja.",
    "Peça feedback rápido: “Ficou confortável? O que não curtiu?”.",
    "Não discuta; ofereça alternativa melhor ou mais adequada.",
    "Aprenda os produtos de memória para não perder tempo procurando.",
    "Revise suas metas no início do turno para saber o alvo do dia.",
    "Transforme cada cliente em oportunidade, não em “curioso”.",
    "Use urgência verdadeira: “Temos poucas unidades desse modelo.”.",
    "Ofereça itens em alta estação (ex.: verão: vestido, sandália, chapéu).",
    "No caixa, pergunte se faltou algo: “Precisa de mais alguma peça hoje?”.",
    "Participe dos desafios internos de vendas, mesmo pequenos.",
    "Observe quais frases funcionam mais e repita as campeãs.",
    "Peça indicações: “Se lembrar de alguém que gosta desse estilo, manda pra cá.”.",
    "Use cheirinho, música e ambiente agradável para segurar o cliente.",
    "Mantenha o setor organizado; bagunça derruba vendas.",
    "Anote rapidamente objeções comuns para treinar respostas melhores.",
    "Ao final, agradeça e convide para voltar em uma data específica.",
  ],
  pa: [
    "Nunca finalize venda com só 1 peça sem oferecer mais nada.",
    "Monte “looks completos”: parte de cima, parte de baixo e acessório.",
    "Use combos prontos: “Leve 3, pague 2” ou descontos progressivos.",
    "Mostre sempre algo complementar ao que o cliente já escolheu.",
    "Coloque produtos pequenos perto do caixa (meias, cintos, acessórios).",
    "Pergunte: “Você já viu esse modelo que combina com o que escolheu?”.",
    "Use o provador para sugerir mais uma peça que combine.",
    "Tenha “kit pronto” para presente (look completo, embalado).",
    "Mostre alternativas de cor: “Esse mesmo modelo tem neste tom também.”.",
    "Ofereça itens de reposição: meias, básicos, peças do dia a dia.",
    "Use o argumento “aproveitar o frete/visita” para levar mais itens.",
    "Explique que combos saem mais em conta que peça solta.",
    "Quando o cliente gosta de uma peça, busque variações (estampa/cor).",
    "Use “regra do 3”: sempre sugira 3 produtos complementares.",
    "Crie desafios internos de PA entre vendedores com premiação.",
    "Tenha frases prontas: “Essa peça fica ótima com…” (e mostra o extra).",
    "Sugira itens de outra categoria que combinam (sapato + roupa).",
    "Use espaços de exposição cruzada (cinto na calça, brinco no manequim).",
    "Revise seu PA no meio do turno e ajuste o foco se estiver baixo.",
    "Quando o cliente pede desconto, ofereça combo em vez de baixar preço.",
    "Deixe produtos “impulso” sempre à mão (biju, cuidado pessoal).",
    "Sugira peça reserva: “Quer levar outra blusa pra revezar?”.",
    "Crie histórias: “Muita gente leva esse conjunto pra viagem/trabalho.”.",
    "Quando atender família, pense em itens para cada pessoa.",
    "Use o tamanho como gancho: “Já quer garantir a mesma peça em outra cor nesse tamanho?”.",
    "Fale do uso em situações diferentes (trabalho + fim de semana).",
    "Tenha tabela mental dos complementares clássicos da loja.",
    "Ofereça proteção e cuidados (lavagem, armazenamento) como item extra.",
    "Destaque produtos com melhor margem nos complementares.",
    "Treine com scripts rápidos de cross-sell com seu time.",
    "Observe o carrinho e pergunte: “Faltou algum item pra completar o look?”.",
    "Use “se levar mais um…” para ativar promoção ou brinde.",
    "Mostre visivelmente kits “prontos para presentear”.",
    "Use exemplos reais: “Ontem uma cliente levou esse conjunto completo.”.",
    "Após cada venda, pergunte se poderia ter sugerido algo a mais e anote ideias.",
  ],
  ticket: [
    "Comece mostrando a opção de maior valor (o “sonho”) e depois desça.",
    "Tenha versão “premium” clara em cada categoria de produto.",
    "Use frase: “Por um pouco a mais você leva este, que dura bem mais.”.",
    "Monte kits com preço fechado que saem mais em conta que avulso.",
    "Use descontos progressivos: 1 peça preço cheio, 2 ou mais com benefício.",
    "Destaque itens de maior margem em pontos nobres da loja.",
    "Deixe o premium na altura dos olhos, o básico mais abaixo.",
    "Mostre comparativo simples: “Esse aqui amassa menos, dura mais, vale a diferença.”.",
    "Ofereça upgrades: tecido melhor, modelo mais atual, marca superior.",
    "Use “kit look completo” com preço maior porém vantajoso.",
    "No caixa, sugira um último item com alto valor percebido.",
    "Promova combos “leve hoje e ganhe X% na próxima compra”.",
    "Use escassez verdadeira nos produtos de maior valor.",
    "Mostre como o produto mais caro resolve melhor o problema do cliente.",
    "Crie vitrines com combinações premium para inspirar.",
    "Treine o time para não ter medo de oferecer opções mais caras.",
    "Use argumento de custo por uso: “Sai centavos por dia se usar o mês inteiro.”.",
    "Ofereça parcelamento confortável para itens mais altos.",
    "Use programas de pontos que recompensam tickets maiores.",
    "Analise quais produtos elevam mais o ticket e foque neles.",
    "Ofereça “seguro”, garantia estendida ou serviço extra quando fizer sentido.",
    "Agrupe produtos por “ocasião” (trabalho, festa, viagem) com preço total maior.",
    "Use cartazes simples: “Sugestão Premium”, “Escolha dos Vendedores”.",
    "Oriente clientes fiéis a conhecer linha nova mais cara primeiro.",
    "Em datas especiais, ofereça pacote presente completo com valor mais alto.",
    "Crie metas de ticket médio por dia e acompanhe de hora em hora.",
    "Compartilhe entre a equipe as frases que mais geram upgrades.",
    "Use storytelling: “Esse tecido é usado em…”, aumentando percepção de valor.",
    "Não ofereça desconto logo de cara; primeiro ofereça valor melhor.",
    "Revise frequentemente exposição e kits para manter novidade e interesse.",
  ]
};

export type TipCategory = keyof typeof tipsData;

/**
 * Retorna uma dica aleatória de uma categoria específica.
 * @param category A categoria da dica ('vendas', 'pa', 'ticket').
 * @returns Uma string com a dica.
 */
export function getRandomTip(category: TipCategory): string {
  const tipsForCategory = tipsData[category];
  if (!tipsForCategory || tipsForCategory.length === 0) {
    return "Continue focado em oferecer o melhor atendimento ao seu cliente!";
  }
  const randomIndex = Math.floor(Math.random() * tipsForCategory.length);
  return tipsForCategory[randomIndex];
}
